.github/workflows/ci.yml
lib/api/api.dart
lib/api/parser.dart
lib/crowd_action_browse_route.dart
lib/dummy_data.dart
lib/main.dart
lib/utilities.dart
test/widget_test.dart

**What was changed:**
- Added basic CI workflow for testing and creating Android debug builds
- Fixed formatting and example test (so the workflow should run to completion)

Feature/8 set up GitHub actions

---

lib/presentation/crowd_action/crowd_action_details.dart
lib/presentation/routes/app_routes.dart
lib/presentation/shared_widgets/custom_appbar.dart
lib/presentation/themes/constants.dart
pubspec.lock
pubspec.yaml

feat(crowdaction-detail): crowdaction detail screen/ui

---

lib/presentation/contact_form/contact_form_screen.dart
lib/presentation/shared_widgets/custom_appbar.dart

`// TODO: Possibly separate into multiple App bars? (ScrollableAppBar, ElevatedAppBar, CleanAppBar)`
^ Will make a task for this. 
Relates: APP-50
Closes: #24

fix(app-bar): new app bar features

---

lib/main.dart
lib/presentation/home/home_screen.dart
lib/presentation/onboarding/onboarding.dart
pubspec.lock
pubspec.yaml

fix(onboarding): show onboarding first time

---

.github/workflows/ci.yml

Fix/app 55/ci firebase

---

.github/workflows/ci.yml

Firebase app distribution in workflow

---

ios/Flutter/Debug.xcconfig
ios/Flutter/Release.xcconfig
ios/Podfile
ios/Podfile.lock
ios/Runner.xcodeproj/project.pbxproj
ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
ios/Runner.xcworkspace/contents.xcworkspacedata
ios/Runner/Runner.entitlements

The initial configuration to run on iOS / Xcode

ios: initial commit

---

.github/workflows/ci.yml
android/app/build.gradle
docs/github.md
pubspec.lock

~⚠ Do not merge! ⚠~
Ready for merging now 🙂

Build appbundle

---

.github/workflows/ci.yml

Fix for https://github.com/CollActionteam/collaction_app/runs/4346955584?check_suite_focus=true

Fixed path to apk

---

lib/presentation/crowd_action/pages/widgets/share_collaction_card.dart

Apple may reject the app if it contains obvious placeholder content or other unfinished features.

Better placeholder text for sharing CollAction

---

.github/workflows/ci.yml
ExportOptions.plist
ios/Runner/Info.plist

~⚠ Do not merge! ⚠~
Building and publishing to Testflight ❗finally❗ work (see https://github.com/CollActionteam/collaction_app/actions/runs/1526142466)

Build ipa directly from flutter cli

---

lib/application/contact_form/contact_form_bloc.dart
lib/application/contact_form/contact_form_event.dart
lib/application/contact_form/contact_form_state.dart
lib/domain/contact_form/contact_form_contents.dart
lib/domain/contact_form/contact_form_dto.dart
lib/domain/contact_form/i_contact_form_api.dart
lib/infrastructure/contact_form/contact_form_api.dart
lib/presentation/contact_form/contact_form_screen.dart
lib/presentation/crowd_action/pages/widgets/share_collaction_card.dart
lib/presentation/shared_widgets/custom_app_bars/custom_appbar.dart
test/screens/contact_form_screen_test.dart
test/test_utilities.dart

New PR to target `development`

feat: contact form changes

---

lib/presentation/auth/auth_screen.dart
lib/presentation/auth/widgets/legal_notice.dart
lib/presentation/auth/widgets/verify_phone.dart

Legal links on registration screen

---

lib/presentation/profile/profile_screen.dart

fix: Hide profile tabs.

---

lib/presentation/crowdaction/crowdaction_details/widgets/confirm_participation.dart

fix: Crowdaction Overflow issue.

---

lib/presentation/profile/profile_screen.dart
lib/presentation/profile/widget/profile_picture.dart

~@Xazin The profile does not get refreshed after registration, but I couldn't figure out what causes this.~

registration button on profile tab, widget for avatar

---

lib/presentation/home/home_screen.dart
lib/presentation/onboarding/onboarding_screen.dart

force onboarding completion

---

lib/presentation/settings/settings_screen.dart

fix: use external link icon

---

lib/application/user/profile/profile_bloc.dart
lib/application/user/profile/profile_state.dart
lib/infrastructure/user/avatar_repository.dart
lib/presentation/core/app_widget.dart
lib/presentation/profile/profile_screen.dart
lib/presentation/shared_widgets/photo_selector.dart
pubspec.lock
pubspec.yaml

Partially fixes #145 
⚠Work in progress! Do not merge yet!

Fix: Update profile picture

---

lib/presentation/contact_form/contact_form_screen.dart
lib/presentation/contact_form/widgets/contact_form.dart
lib/presentation/home/captive_screen.dart
lib/presentation/utils/mvp.dart

* Launch captive screen on 2022-02-01
* Design of link on captive screen
* Access settings from captive screen (Not sure about this last commit, since it was commented out previously, but it is in the design and having it makes sense)

Final changes before release

---

.env.example
ios/Runner/Info.plist
lib/application/user/profile/profile_bloc.dart
lib/application/user/profile/profile_state.dart
lib/infrastructure/user/avatar_repository.dart
lib/presentation/auth/widgets/legal_notice.dart
lib/presentation/contact_form/contact_form_screen.dart
lib/presentation/contact_form/widgets/contact_form.dart
lib/presentation/core/app_widget.dart
lib/presentation/home/captive_screen.dart
lib/presentation/home/home_screen.dart
lib/presentation/onboarding/onboarding_screen.dart
lib/presentation/profile/profile_screen.dart
lib/presentation/profile/widget/profile_picture.dart
lib/presentation/settings/settings_screen.dart
lib/presentation/shared_widgets/photo_selector.dart
lib/presentation/utils/launch_url.dart
lib/presentation/utils/mvp.dart
pubspec.lock
pubspec.yaml

This is probably going to be the cleanest way to go about this in the future, merge master into development, open PR, and merge it.
Since we squash commits on merging to master, we can only really use it for release, which is fine and that's what we are doing, but rebasing on it is then impossible (near impossible at least).

Chore: merge master into development

---

docs/CONTRIBUTING.md

First step in having contribution guidelines.
Closes: #76

docs: add contribution guidelines

---

.github/workflows/ci.yml

Let's try this out.
Closes: #171

chore: add workflow_dispatch

---

.github/workflows/ci.yml

removed apk steps from workflow

---

pubspec.yaml

chore: update app version to 1.1.0

---

lib/presentation/home/home_screen.dart

192 [Bug]: Remove elevation from navigation bar

---

lib/domain/crowdaction/crowdaction.dart
lib/presentation/crowdaction/crowdaction_details/crowdaction_details_screen.dart
lib/presentation/shared_widgets/accent_chip.dart
lib/presentation/shared_widgets/micro_crowdaction_card.dart

Sign Up button chip should display Open/Closed basing on state.
Closes #184

184 [Feature]: Changes to the "Sign up now" chip

---

lib/presentation/core/app_widget.dart
lib/presentation/home/home_screen.dart

chore: deactivate captive screen

---

lib/presentation/auth/auth_screen.dart
lib/presentation/contact_form/contact_form_screen.dart
lib/presentation/crowdaction/crowdaction_browse/crowdaction_browse_screen.dart
lib/presentation/licenses/licenses_page.dart
lib/presentation/settings/settings_screen.dart
lib/presentation/shared_widgets/custom_app_bars/custom_appbar.dart

refactor: use build context synchronously

---

lib/presentation/settings/settings_screen.dart
lib/presentation/settings/widgets/settings_list_tile.dart

fix: refactor and fix settings list items

---

lib/presentation/profile/profile_screen.dart
pubspec.lock

Share FAB is implemented also the icons doesn't scroll with the list as was the bug earlier.

enhance: Share FAB implemented

---

android/app/build.gradle
lib/presentation/auth/widgets/legal_notice.dart
lib/presentation/routes/app_routes.dart
lib/presentation/shared_widgets/web_view_page.dart
lib/presentation/utils/launch_url.dart
pubspec.lock
pubspec.yaml

Let me know if this doesn't fulfill the criteria @rubenhorn 
Closes: #167

feat: open webview on a screen

---

lib/presentation/crowdaction/crowdaction_details/crowdaction_details_screen.dart
lib/presentation/shared_widgets/expandable_text.dart

feat(crowdaction): Expandable text for CrowdAction description.

---

lib/api/queries/crowdaction_queries.dart
lib/application/crowdaction/subscription/subscription_bloc.dart
lib/application/crowdaction/subscription/subscription_event.dart
lib/application/crowdaction/subscription/subscription_state.dart
lib/application/crowdaction/subscription_status/subscription_status_bloc.dart
lib/application/crowdaction/subscription_status/subscription_status_state.dart
lib/presentation/crowdaction/crowdaction_details/crowdaction_details_screen.dart
lib/presentation/crowdaction/crowdaction_details/widgets/confirm_participation.dart
lib/presentation/crowdaction/crowdaction_details/widgets/withdraw_participation.dart
lib/presentation/shared_widgets/commitments/commitment_card.dart
lib/presentation/shared_widgets/commitments/commitment_card_list.dart
lib/presentation/themes/constants.dart
pubspec.lock

Gray out commits when participating

---

lib/domain/crowdaction/crowdaction.dart
lib/presentation/crowdaction/crowdaction_details/crowdaction_details_screen.dart
lib/presentation/crowdaction/crowdaction_home/widgets/share_collaction_button.dart
lib/presentation/crowdaction/crowdaction_home/widgets/share_collaction_card.dart
lib/presentation/onboarding/widgets/onboarding_step.dart
lib/presentation/settings/widgets/share_collaction_list_tile.dart
lib/presentation/shared_widgets/crowdaction_card.dart
lib/presentation/shared_widgets/custom_fab.dart
lib/presentation/shared_widgets/micro_crowdaction_card.dart
lib/presentation/shared_widgets/micro_lock.dart

feat: add lock fab to crowdactions

---

lib/presentation/home/widgets/password_modal.dart

fix: padding of password dialog

---

lib/infrastructure/crowdaction/crowdaction_repository.dart
lib/infrastructure/profile/profile_repository.dart
lib/infrastructure/user/avatar_repository.dart
lib/presentation/settings/settings_screen.dart
lib/presentation/shared_widgets/web_view_page.dart

feat: changes to webview

---

.github/workflows/ci.yml
.gitignore
codecov.yml

setup for tracking code coverage with Codecov and GitHub Actions.

added test coverage files

---

.github/workflows/ci.yml
lib/domain/user/user.dart
lib/presentation/home/home_screen.dart
lib/presentation/shared_widgets/photo_selector.dart
pubspec.lock
pubspec.yaml
test/domain/profile/user_profile_test.dart
test/test_utilities.dart

Upgraded project to flutter `3.0.3`. Upgraded dependencies to the latest compatible version.

upgraded project to flutter 3.0.3 and updated dependencies

---

lib/application/user/profile/profile_bloc.dart
lib/application/user/profile/profile_state.dart
lib/domain/profile/profile.dart
lib/infrastructure/profile/profile_dto.dart
lib/infrastructure/profile/profile_repository.dart
test/application/user/profile/profile_bloc_test.dart
test/domain/profile/profile_fixture.dart
test/domain/user/user_fixture.dart
test/infrastructure/profile/profile_repository_test.dart
test/test_utilities.dart

When a user’s profile is missing, the profile shows the login/create account option even when firebase is already signed in successfully.
Fix
- Attempt to load the profile normally.
- If the load attempts fails with 500 error, attempt to create a base profile for the user.
- Finally reload the created profile.

bug(profile): Fix profile loading bug

---

lib/presentation/settings/settings_screen.dart

fix(settings): Remove Contact Us.

---

lib/presentation/auth/widgets/verification_code.dart
lib/presentation/shared_widgets/pin_input/pin_input.dart
lib/presentation/shared_widgets/pin_input/pin_text_field.dart
test/presentation/shared_widgets/pin_input/mocks.dart
test/presentation/shared_widgets/pin_input/pin_input_test.dart
test/presentation/shared_widgets/pin_input/pin_input_test.ext.dart

Closes #275 
**Before:**
https://user-images.githubusercontent.com/15793624/189472912-b7fa7dd3-5743-41f4-a775-f44f99096c98.mp4
**After:**
https://user-images.githubusercontent.com/15793624/189472911-23a533fe-8ce6-4a0c-ae82-a70000883c09.mp4

bug(auth): Pasting PIN not working.

---

lib/presentation/profile/widget/profile_picture.dart

Closes #277 
https://user-images.githubusercontent.com/15793624/189473946-30375011-68a6-48d7-8783-f85a3d677c36.mp4

fix(profile): Set Profile Image Placeholder.

---

.github/workflows/ci.yml
ios/Flutter/AppFrameworkInfo.plist
ios/Podfile.lock
lib/domain/auth/auth_failures.dart
lib/domain/crowdaction/crowdaction_failures.dart
lib/domain/crowdaction/crowdaction_status.dart
lib/domain/user/profile_failure.dart
lib/domain/user/upload_failures.dart
lib/infrastructure/core/settings_repository.dart
lib/presentation/crowdaction/crowdaction_home/widgets/in_spotlight_header.dart
lib/presentation/crowdaction/crowdaction_home/widgets/share_collaction_card.dart
lib/presentation/home/captive_screen.dart
lib/presentation/home/widgets/password_modal.dart
lib/presentation/licenses/licenses_page.dart
lib/presentation/profile/profile_screen.dart
lib/presentation/profile/widget/profile_tab.dart
lib/presentation/routes/app_routes.dart
lib/presentation/shared_widgets/custom_app_bars/custom_appbar.dart
lib/presentation/shared_widgets/participant_avatars.dart
lib/presentation/shared_widgets/phone_input.dart
lib/presentation/shared_widgets/pill_button.dart
lib/presentation/themes/themes.dart
pubspec.lock
pubspec.yaml
test/domain/profile/user_profile_test.dart
test/infrastructure/profile/profile_repository_test.dart
test/user_repository/user_repository_tests.dart

core(update): Update flutter to 3.3.2 & Upgrade dependencies as well.

---

lib/application/auth/auth_bloc.dart
lib/application/auth/auth_state.dart
lib/presentation/profile/widget/profile_picture.dart
lib/presentation/shared_widgets/crowdaction_card.dart
lib/presentation/shared_widgets/micro_crowdaction_card.dart
pubspec.lock

Need to introduce another state to handle when signing out is initialized, and after that is successful, then logout is emit. This resolved the issue for me, please verify.

fix: logout successful after 2 tries

---

pubspec.lock
pubspec.yaml

This PR is associated with this Suggestion -> https://github.com/CollActionteam/collaction_app/issues/286

added ionicons dependency

---

test/infrastructure/crowdaction/location_dto_fixtures.dart
test/infrastructure/crowdaction/location_dto_test.dart

Completed Location DTO unit test by creating the associated Location DTO fixtures file and Location DTO test file.  Test ran and completed with no issues.

Feat/gh 224/tests location dto

---

lib/domain/crowdaction/crowdaction.dart
lib/infrastructure/crowdaction/crowdaction_dto.dart
test/domain/crowdaction/crowdaction_test_fixtures.dart
test/infrastructure/participation/participation_dto_fixtures.dart
test/infrastructure/participation/participation_dto_test.dart
test/infrastructure/participation/participation_fixtures.dart

created participation dto fixtures file, participation dto test file, deleted all code associated with TopParticipant and TopParticipantDTO, ran test with no issues.

Feat/gh 224/test participation dto

---

test/infrastructure/crowdaction/paginated_crowdactions_dto_fixtures.dart
test/infrastructure/crowdaction/paginated_crowdactions_dto_test.dart

created paginated crowdactions dto fixtures file, created paginated crowdactions dto test file, ran with no errors.

Feat/gh 224/test paginated crowdactions dto

---

test/application/crowdaction/crowdaction_details/crowdaction_details_bloc.mocks.dart
test/application/participation/top_participants/top_participants_bloc.mocks.dart
test/presentation/router.mocks.dart
test/presentation/shared_widgets/crowdaction_card_test.dart
test/presentation/shared_widgets/crowdaction_card_test.ext.dart
test/test_utilities.dart

Navigation testing with auto_route using `CrowdActionCard` as specimen.

test: CrowdActionCard navigation

---

test/infrastructure/auth/firebase_auth_repository_test.dart
test/infrastructure/contact_form/contact_form_dto_fixtures.dart
test/infrastructure/contact_form/contact_form_repository_test.dart
test/presentation/crowdaction/crowdaction_home/in_spotlight_header_test.dart

tests: 
- firebase auth repo
- contact form repo

Infrastructure Tests

---

.github/workflows/ci.yml

cicd: refactor to environment secrets

---

lib/domain/auth/i_auth_repository.dart
lib/infrastructure/auth/firebase_auth_repository.dart
lib/infrastructure/participation/participation_repository.dart
lib/presentation/crowdaction/crowdaction_details/widgets/participants.dart
lib/presentation/crowdaction/crowdaction_participants/crowdaction_participants_screen.dart
test/infrastructure/participation/participation_repository_fixtures.dart
test/infrastructure/participation/participation_repository_test.dart

fix(`participants`): Show current user as lead participant.
